name: diaspro_markdown_mobile
description: Editor Markdown mobile leggero in stile Diaspro.
publish_to: none
version: 1.0.1+2

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown_plus: ^1.0.12

flutter:
  uses-material-design: true
